import catalog1Items from './catalog1Items.json';

export const CATALOG_SECTIONS = [
  {
    key: 'living-room',
    title: 'Living Room Furniture',
    image: '/catalog/section_pages/living-room-p002.jpeg',
    itemCount: 84,
  },
  {
    key: 'bedroom',
    title: 'Bedroom Furniture',
    image: '/catalog/section_pages/bedroom-p058.jpeg',
    itemCount: 11,
  },
  {
    key: 'dining-room',
    title: 'Dining Room Furniture',
    image: '/catalog/section_pages/dining-room-p041.jpeg',
    itemCount: 17,
  },
];

export const CATALOG_ITEMS_BY_SECTION = {
  'living-room': [
    {
      id: 'living-room-001',
      title: "Living Room Collection 1",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p002.jpeg',
      sourcePage: 2,
    },
    {
      id: 'living-room-002',
      title: "Living Room Collection 2",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p003.jpeg',
      sourcePage: 3,
    },
    {
      id: 'living-room-003',
      title: "Living Room Collection 3",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p004.jpeg',
      sourcePage: 4,
    },
    {
      id: 'living-room-004',
      title: "Living Room Collection 4",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p005.jpeg',
      sourcePage: 5,
    },
    {
      id: 'living-room-005',
      title: "Living Room Collection 5",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p006.jpeg',
      sourcePage: 6,
    },
    {
      id: 'living-room-006',
      title: "Living Room Collection 6",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p007.jpeg',
      sourcePage: 7,
    },
    {
      id: 'living-room-007',
      title: "Living Room Collection 7",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p008.jpeg',
      sourcePage: 8,
    },
    {
      id: 'living-room-008',
      title: "Living Room Collection 8",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p009.jpeg',
      sourcePage: 9,
    },
    {
      id: 'living-room-009',
      title: "Living Room Collection 9",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p010.jpeg',
      sourcePage: 10,
    },
    {
      id: 'living-room-010',
      title: "Living Room Collection 10",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p011.jpeg',
      sourcePage: 11,
    },
    {
      id: 'living-room-011',
      title: "Living Room Collection 11",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p012.jpeg',
      sourcePage: 12,
    },
    {
      id: 'living-room-012',
      title: "Living Room Collection 12",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p013.jpeg',
      sourcePage: 13,
    },
    {
      id: 'living-room-013',
      title: "Living Room Collection 13",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p014.jpeg',
      sourcePage: 14,
    },
    {
      id: 'living-room-014',
      title: "Living Room Collection 14",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p015.jpeg',
      sourcePage: 15,
    },
    {
      id: 'living-room-015',
      title: "Living Room Collection 15",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p016.jpeg',
      sourcePage: 16,
    },
    {
      id: 'living-room-016',
      title: "Living Room Collection 16",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p017.jpeg',
      sourcePage: 17,
    },
    {
      id: 'living-room-017',
      title: "Living Room Collection 17",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p018.jpeg',
      sourcePage: 18,
    },
    {
      id: 'living-room-018',
      title: "Living Room Collection 18",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p019.jpeg',
      sourcePage: 19,
    },
    {
      id: 'living-room-019',
      title: "Living Room Collection 19",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p020.jpeg',
      sourcePage: 20,
    },
    {
      id: 'living-room-020',
      title: "Living Room Collection 20",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p021.jpeg',
      sourcePage: 21,
    },
    {
      id: 'living-room-021',
      title: "Living Room Collection 21",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p022.jpeg',
      sourcePage: 22,
    },
    {
      id: 'living-room-022',
      title: "Living Room Collection 22",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p023.jpeg',
      sourcePage: 23,
    },
    {
      id: 'living-room-023',
      title: "Living Room Collection 23",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p024.jpeg',
      sourcePage: 24,
    },
    {
      id: 'living-room-024',
      title: "Living Room Collection 24",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p025.jpeg',
      sourcePage: 25,
    },
    {
      id: 'living-room-025',
      title: "Living Room Collection 25",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p026.jpeg',
      sourcePage: 26,
    },
    {
      id: 'living-room-026',
      title: "Living Room Collection 26",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p027.jpeg',
      sourcePage: 27,
    },
    {
      id: 'living-room-027',
      title: "Living Room Collection 27",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p028.jpeg',
      sourcePage: 28,
    },
    {
      id: 'living-room-028',
      title: "Living Room Collection 28",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p029.jpeg',
      sourcePage: 29,
    },
    {
      id: 'living-room-029',
      title: "Living Room Collection 29",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p030.jpeg',
      sourcePage: 30,
    },
    {
      id: 'living-room-030',
      title: "Living Room Collection 30",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p031.jpeg',
      sourcePage: 31,
    },
    {
      id: 'living-room-031',
      title: "Living Room Collection 31",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p032.jpeg',
      sourcePage: 32,
    },
    {
      id: 'living-room-032',
      title: "Living Room Collection 32",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p033.jpeg',
      sourcePage: 33,
    },
    {
      id: 'living-room-033',
      title: "Living Room Collection 33",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p034.jpeg',
      sourcePage: 34,
    },
    {
      id: 'living-room-034',
      title: "Living Room Collection 34",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p035.jpeg',
      sourcePage: 35,
    },
    {
      id: 'living-room-035',
      title: "Living Room Collection 35",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p036.jpeg',
      sourcePage: 36,
    },
    {
      id: 'living-room-036',
      title: "Living Room Collection 36",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p037.jpeg',
      sourcePage: 37,
    },
    {
      id: 'living-room-037',
      title: "Living Room Collection 37",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p038.jpeg',
      sourcePage: 38,
    },
    {
      id: 'living-room-038',
      title: "Living Room Collection 38",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p039.jpeg',
      sourcePage: 39,
    },
    {
      id: 'living-room-039',
      title: "Living Room Collection 39",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p040.jpeg',
      sourcePage: 40,
    },
    {
      id: 'living-room-040',
      title: "Living Room Collection 40",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p069.jpeg',
      sourcePage: 69,
    },
    {
      id: 'living-room-041',
      title: "Living Room Collection 41",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p070.jpeg',
      sourcePage: 70,
    },
    {
      id: 'living-room-042',
      title: "Living Room Collection 42",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p071.jpeg',
      sourcePage: 71,
    },
    {
      id: 'living-room-043',
      title: "Living Room Collection 43",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p072.jpeg',
      sourcePage: 72,
    },
    {
      id: 'living-room-044',
      title: "Living Room Collection 44",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p073.jpeg',
      sourcePage: 73,
    },
    {
      id: 'living-room-045',
      title: "Living Room Collection 45",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p074.jpeg',
      sourcePage: 74,
    },
    {
      id: 'living-room-046',
      title: "Living Room Collection 46",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p075.jpeg',
      sourcePage: 75,
    },
    {
      id: 'living-room-047',
      title: "Living Room Collection 47",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p076.jpeg',
      sourcePage: 76,
    },
    {
      id: 'living-room-048',
      title: "Living Room Collection 48",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p077.jpeg',
      sourcePage: 77,
    },
    {
      id: 'living-room-049',
      title: "Living Room Collection 49",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p078.jpeg',
      sourcePage: 78,
    },
    {
      id: 'living-room-050',
      title: "Living Room Collection 50",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p079.jpeg',
      sourcePage: 79,
    },
    {
      id: 'living-room-051',
      title: "Living Room Collection 51",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p080.jpeg',
      sourcePage: 80,
    },
    {
      id: 'living-room-052',
      title: "Living Room Collection 52",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p081.jpeg',
      sourcePage: 81,
    },
    {
      id: 'living-room-053',
      title: "Living Room Collection 53",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p082.jpeg',
      sourcePage: 82,
    },
    {
      id: 'living-room-054',
      title: "Living Room Collection 54",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p083.jpeg',
      sourcePage: 83,
    },
    {
      id: 'living-room-055',
      title: "Living Room Collection 55",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p084.jpeg',
      sourcePage: 84,
    },
    {
      id: 'living-room-056',
      title: "Living Room Collection 56",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p085.jpeg',
      sourcePage: 85,
    },
    {
      id: 'living-room-057',
      title: "Living Room Collection 57",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p086.jpeg',
      sourcePage: 86,
    },
    {
      id: 'living-room-058',
      title: "Living Room Collection 58",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p087.jpeg',
      sourcePage: 87,
    },
    {
      id: 'living-room-059',
      title: "Living Room Collection 59",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p088.jpeg',
      sourcePage: 88,
    },
    {
      id: 'living-room-060',
      title: "Living Room Collection 60",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p089.jpeg',
      sourcePage: 89,
    },
    {
      id: 'living-room-061',
      title: "Living Room Collection 61",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p090.jpeg',
      sourcePage: 90,
    },
    {
      id: 'living-room-062',
      title: "Living Room Collection 62",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p091.jpeg',
      sourcePage: 91,
    },
    {
      id: 'living-room-063',
      title: "Living Room Collection 63",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p092.jpeg',
      sourcePage: 92,
    },
    {
      id: 'living-room-064',
      title: "Living Room Collection 64",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p093.jpeg',
      sourcePage: 93,
    },
    {
      id: 'living-room-065',
      title: "Living Room Collection 65",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p094.jpeg',
      sourcePage: 94,
    },
    {
      id: 'living-room-066',
      title: "Living Room Collection 66",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p095.jpeg',
      sourcePage: 95,
    },
    {
      id: 'living-room-067',
      title: "Living Room Collection 67",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p096.jpeg',
      sourcePage: 96,
    },
    {
      id: 'living-room-068',
      title: "Living Room Collection 68",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p097.jpeg',
      sourcePage: 97,
    },
    {
      id: 'living-room-069',
      title: "Living Room Collection 69",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p098.jpeg',
      sourcePage: 98,
    },
    {
      id: 'living-room-070',
      title: "Living Room Collection 70",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p099.jpeg',
      sourcePage: 99,
    },
    {
      id: 'living-room-071',
      title: "Living Room Collection 71",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p100.jpeg',
      sourcePage: 100,
    },
    {
      id: 'living-room-072',
      title: "Living Room Collection 72",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p101.jpeg',
      sourcePage: 101,
    },
    {
      id: 'living-room-073',
      title: "Living Room Collection 73",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p102.jpeg',
      sourcePage: 102,
    },
    {
      id: 'living-room-074',
      title: "Living Room Collection 74",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p103.jpeg',
      sourcePage: 103,
    },
    {
      id: 'living-room-075',
      title: "Living Room Collection 75",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p104.jpeg',
      sourcePage: 104,
    },
    {
      id: 'living-room-076',
      title: "Living Room Collection 76",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p105.jpeg',
      sourcePage: 105,
    },
    {
      id: 'living-room-077',
      title: "Living Room Collection 77",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p106.jpeg',
      sourcePage: 106,
    },
    {
      id: 'living-room-078',
      title: "Living Room Collection 78",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p107.jpeg',
      sourcePage: 107,
    },
    {
      id: 'living-room-079',
      title: "Living Room Collection 79",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p108.jpeg',
      sourcePage: 108,
    },
    {
      id: 'living-room-080',
      title: "Living Room Collection 80",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p109.jpeg',
      sourcePage: 109,
    },
    {
      id: 'living-room-081',
      title: "Living Room Collection 81",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p110.jpeg',
      sourcePage: 110,
    },
    {
      id: 'living-room-082',
      title: "Living Room Collection 82",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p111.jpeg',
      sourcePage: 111,
    },
    {
      id: 'living-room-083',
      title: "Living Room Collection 83",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p112.jpeg',
      sourcePage: 112,
    },
    {
      id: 'living-room-084',
      title: "Living Room Collection 84",
      description: "French-style living room furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/living-room-p113.jpeg',
      sourcePage: 113,
    },
  ],
  'bedroom': [
    {
      id: 'bedroom-001',
      title: "Bedroom Collection 1",
      description: "French-style bedroom furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/bedroom-p058.jpeg',
      sourcePage: 58,
    },
    {
      id: 'bedroom-002',
      title: "Bedroom Collection 2",
      description: "French-style bedroom furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/bedroom-p059.jpeg',
      sourcePage: 59,
    },
    {
      id: 'bedroom-003',
      title: "Bedroom Collection 3",
      description: "French-style bedroom furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/bedroom-p060.jpeg',
      sourcePage: 60,
    },
    {
      id: 'bedroom-004',
      title: "Bedroom Collection 4",
      description: "French-style bedroom furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/bedroom-p061.jpeg',
      sourcePage: 61,
    },
    {
      id: 'bedroom-005',
      title: "Bedroom Collection 5",
      description: "French-style bedroom furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/bedroom-p062.jpeg',
      sourcePage: 62,
    },
    {
      id: 'bedroom-006',
      title: "Bedroom Collection 6",
      description: "French-style bedroom furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/bedroom-p063.jpeg',
      sourcePage: 63,
    },
    {
      id: 'bedroom-007',
      title: "Bedroom Collection 7",
      description: "French-style bedroom furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/bedroom-p064.jpeg',
      sourcePage: 64,
    },
    {
      id: 'bedroom-008',
      title: "Bedroom Collection 8",
      description: "French-style bedroom furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/bedroom-p065.jpeg',
      sourcePage: 65,
    },
    {
      id: 'bedroom-009',
      title: "Bedroom Collection 9",
      description: "French-style bedroom furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/bedroom-p066.jpeg',
      sourcePage: 66,
    },
    {
      id: 'bedroom-010',
      title: "Bedroom Collection 10",
      description: "French-style bedroom furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/bedroom-p067.jpeg',
      sourcePage: 67,
    },
    {
      id: 'bedroom-011',
      title: "Bedroom Collection 11",
      description: "French-style bedroom furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/bedroom-p068.jpeg',
      sourcePage: 68,
    },
  ],
  'dining-room': [
    {
      id: 'dining-room-001',
      title: "Dining Room Collection 1",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p041.jpeg',
      sourcePage: 41,
    },
    {
      id: 'dining-room-002',
      title: "Dining Room Collection 2",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p042.jpeg',
      sourcePage: 42,
    },
    {
      id: 'dining-room-003',
      title: "Dining Room Collection 3",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p043.jpeg',
      sourcePage: 43,
    },
    {
      id: 'dining-room-004',
      title: "Dining Room Collection 4",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p044.jpeg',
      sourcePage: 44,
    },
    {
      id: 'dining-room-005',
      title: "Dining Room Collection 5",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p045.jpeg',
      sourcePage: 45,
    },
    {
      id: 'dining-room-006',
      title: "Dining Room Collection 6",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p046.jpeg',
      sourcePage: 46,
    },
    {
      id: 'dining-room-007',
      title: "Dining Room Collection 7",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p047.jpeg',
      sourcePage: 47,
    },
    {
      id: 'dining-room-008',
      title: "Dining Room Collection 8",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p048.jpeg',
      sourcePage: 48,
    },
    {
      id: 'dining-room-009',
      title: "Dining Room Collection 9",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p049.jpeg',
      sourcePage: 49,
    },
    {
      id: 'dining-room-010',
      title: "Dining Room Collection 10",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p050.jpeg',
      sourcePage: 50,
    },
    {
      id: 'dining-room-011',
      title: "Dining Room Collection 11",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p051.jpeg',
      sourcePage: 51,
    },
    {
      id: 'dining-room-012',
      title: "Dining Room Collection 12",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p052.jpeg',
      sourcePage: 52,
    },
    {
      id: 'dining-room-013',
      title: "Dining Room Collection 13",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p053.jpeg',
      sourcePage: 53,
    },
    {
      id: 'dining-room-014',
      title: "Dining Room Collection 14",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p054.jpeg',
      sourcePage: 54,
    },
    {
      id: 'dining-room-015',
      title: "Dining Room Collection 15",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p055.jpeg',
      sourcePage: 55,
    },
    {
      id: 'dining-room-016',
      title: "Dining Room Collection 16",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p056.jpeg',
      sourcePage: 56,
    },
    {
      id: 'dining-room-017',
      title: "Dining Room Collection 17",
      description: "French-style dining furniture set curated from the provided catalog PDF.",
      dimensions: "Dimensions not listed in the provided PDF",
      image: '/catalog/section_pages/dining-room-p057.jpeg',
      sourcePage: 57,
    },
  ],
};

const SECTION_LABELS = {
  'living-room': 'Living Room',
  bedroom: 'Bedroom',
  'dining-room': 'Dining Room',
};

const SECTION_DESCRIPTIONS = {
  'living-room': 'French-style living room furniture set extracted from Catalog 1 PDF.',
  bedroom: 'French-style bedroom furniture set extracted from Catalog 1 PDF.',
  'dining-room': 'French-style dining furniture set extracted from Catalog 1 PDF.',
};

const sectionCounters = Object.fromEntries(
  Object.entries(CATALOG_ITEMS_BY_SECTION).map(([sectionKey, items]) => [sectionKey, items.length]),
);

for (const item of catalog1Items) {
  const sectionKey = item.section;
  const targetItems = CATALOG_ITEMS_BY_SECTION[sectionKey];

  if (!targetItems) {
    continue;
  }

  sectionCounters[sectionKey] += 1;
  const sequence = String(sectionCounters[sectionKey]).padStart(3, '0');
  const sectionLabel = SECTION_LABELS[sectionKey] || 'Catalog';

  targetItems.push({
    id: `${sectionKey}-${sequence}`,
    title: `${sectionLabel} Collection ${sectionCounters[sectionKey]} (Catalog 1)`,
    description: SECTION_DESCRIPTIONS[sectionKey] || 'Furniture set extracted from Catalog 1 PDF.',
    dimensions: item.dimensions || 'Dimensions not listed in Catalog 1 PDF',
    image: item.image,
    sourcePage: item.sourcePage,
    setCode: item.setCode || null,
  });
}

for (const section of CATALOG_SECTIONS) {
  section.itemCount = (CATALOG_ITEMS_BY_SECTION[section.key] || []).length;
}
